In [ ]:
import pandas as pd

In [ ]:
stu_df = pd.DataFrame([['Shiva',1,'BE'],['Usha',2,'MCA'],['Shubham',3,'Btech']],columns = ['Name','RollNo','Qualification'])

In [ ]:
stu_df

Name  RollNo Qualification
0    Shiva       1            BE
1     Usha       2           MCA
2  Shubham       3         Btech

In [ ]:
stu_dict = {'Name':['Shiva','Usha','Shubham'], 'Rollno':[1,2,3],'Qualification':['BE','MCA','BTech']}

In [ ]:
stu_dict

{'Name': ['Shiva', 'Usha', 'Shubham'],
 'Rollno': [1, 2, 3],
 'Qualification': ['BE', 'MCA', 'BTech']}

In [ ]:
stu_df1 = pd.DataFrame(stu_dict)

In [ ]:
stu_df1

Name  Rollno Qualification
0    Shiva       1            BE
1     Usha       2           MCA
2  Shubham       3         BTech

In [ ]:
df = pd.DataFrame([['Sudeep',3545,'MBA'],['Ruchika',1254,'MCA'],['Rahul',6547,'MS'],['Purnima',1389,'BE']],columns = ['Name','RollNo','Qualification'])

In [ ]:
df

Name  RollNo Qualification
0   Sudeep    3545           MBA
1  Ruchika    1254           MCA
2    Rahul    6547            MS
3  Purnima    1389            BE

In [ ]:
mydf = df.iloc[[0,2]]

In [ ]:
mydf

#creating another dataframe or subset of existing dataframe
#according to df the rahul's index is 2
#but according to mydf rahul's index becomes 1 internally but it will be displayed as 2 externally. we need to change only for
#our display purpose.

Name  RollNo Qualification
0  Sudeep    3545           MBA
2   Rahul    6547            MS

In [ ]:
mydf.iloc[1]

Name             Rahul
RollNo            6547
Qualification       MS
Name: 2, dtype: object

In [ ]:
len(mydf)

2

In [ ]:
mydf.index = range(len(mydf))

#changing the indexes of mydf dataframe

In [ ]:
mydf

Name  RollNo Qualification
0  Sudeep    3545           MBA
1   Rahul    6547            MS

In [3]:
import os

In [5]:
os.chdir(r'/content/drive/MyDrive/STATSCDAC')


In [6]:
os.getcwd()

'/content/drive/MyDrive/STATSCDAC'

In [ ]:
df = pd.read_excel('ERPData.xlsx')

In [ ]:
df.head()

MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [ ]:
df.shape

(50, 3)

In [ ]:
df.Quantity #or df['Quantity']

0      34
1      67
2      27
3      65
4      36
5      78
6      31
7      29
8      10
9     120
10     34
11     58
12     76
13     32
14     65
15     87
16     12
17    102
18     34
19     52
20     39
21     75
22     48
23     71
24    152
25    109
26     57
27     83
28     34
29     57
30     27
31     65
32     43
33    112
34     26
35     31
36     28
37     65
38     70
39    145
40     34
41     57
42     31
43     38
44     42
45     69
46     85
47     29
48     75
49     39
Name: Quantity, dtype: int64

In [ ]:
df['Quantity']

0      34
1      67
2      27
3      65
4      36
5      78
6      31
7      29
8      10
9     120
10     34
11     58
12     76
13     32
14     65
15     87
16     12
17    102
18     34
19     52
20     39
21     75
22     48
23     71
24    152
25    109
26     57
27     83
28     34
29     57
30     27
31     65
32     43
33    112
34     26
35     31
36     28
37     65
38     70
39    145
40     34
41     57
42     31
43     38
44     42
45     69
46     85
47     29
48     75
49     39
Name: Quantity, dtype: int64

In [ ]:
x = list(df['Quantity'])

In [ ]:
x[:5]

[34, 67, 27, 65, 36]

In [ ]:
len(x)

50

In [ ]:
df[df['Quantity']>=75]

#display materialid, location where quantity >=75
#this is done using AMAR sir's method

MaterialID Location  Quantity
5     TMI-43T    MWH-4        78
9     TMI-43T    MWH-1       120
12    TMI-43T    MWH-4        76
15    GCVB-79    MWH-2        87
17    SDRT-67    MWH-5       102
21    TMI-43T    MWH-4        75
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
27    LXCV-21    MWH-5        83
33    TMI-43T    MWH-5       112
39    AXCP-78    MWH-1       145
46    AXCP-78    MWH-2        85
48    AXCP-78    MWH-1        75

In [ ]:
import numpy as np

In [ ]:
x = np.array(df['Quantity'])
#how many values are >=75

In [ ]:
ind = np.where(x>=75)

In [ ]:
ind

(array([ 5,  9, 12, 15, 17, 21, 24, 25, 27, 33, 39, 46, 48]),)

In [ ]:
len(ind[0])

13

In [ ]:
(x>=75).sum()

13

In [ ]:
#in how many Locations MWH-3 is present
x = np.array(df['Location'])

In [ ]:
(x == 'MWH-3').sum()

4

In [ ]:
(df['Location']=='MWH-3').sum()

4

In [ ]:
#make a sepaate df where quantity>=75
#we already have indexes in ind
#ind is the list of indexes
ind

(array([ 5,  9, 12, 15, 17, 21, 24, 25, 27, 33, 39, 46, 48]),)

In [ ]:
mydf = df.iloc[ind]

In [ ]:
mydf

MaterialID Location  Quantity
5     TMI-43T    MWH-4        78
9     TMI-43T    MWH-1       120
12    TMI-43T    MWH-4        76
15    GCVB-79    MWH-2        87
17    SDRT-67    MWH-5       102
21    TMI-43T    MWH-4        75
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
27    LXCV-21    MWH-5        83
33    TMI-43T    MWH-5       112
39    AXCP-78    MWH-1       145
46    AXCP-78    MWH-2        85
48    AXCP-78    MWH-1        75

In [ ]:
mydf.iloc[[0,1,2]]

MaterialID Location  Quantity
5     TMI-43T    MWH-4        78
9     TMI-43T    MWH-1       120
12    TMI-43T    MWH-4        76

In [ ]:
#display where quantity>=100 and location is 'MWH-5'

df[(df['Quantity']>=100) & (df['Location']=='MWH-5')]

MaterialID Location  Quantity
17    SDRT-67    MWH-5       102
33    TMI-43T    MWH-5       112

In [ ]:
df[(df.Quantity>=100) & (df.Location=='MWH-5')]

MaterialID Location  Quantity
17    SDRT-67    MWH-5       102
33    TMI-43T    MWH-5       112

In [ ]:
#SIR's method

ind = np.where((df['Quantity']>=100) & (df['Location']=='MWH-5'))

In [ ]:
ind

(array([17, 33]),)

In [ ]:
mydf = df.iloc[ind]


In [ ]:
mydf

MaterialID Location  Quantity
17    SDRT-67    MWH-5       102
33    TMI-43T    MWH-5       112

In [ ]:
#display the values where qunatity is >=100  OR it is TMI-43T

ind = np.where((df['Quantity']>=100) | (df['MaterialID']=='TMI-43T'))

In [ ]:
ind

(array([ 0,  5,  6,  7,  9, 12, 13, 14, 17, 18, 19, 20, 21, 24, 25, 31, 32,
        33, 39]),)

In [ ]:
mydf = df.iloc[ind]
mydf

MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
9     TMI-43T    MWH-1       120
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
39    AXCP-78    MWH-1       145

In [ ]:
#amar sir method
df1 = df[(df.Quantity>=100)|(df.MaterialID == 'TMI-43T')]
df1

MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
9     TMI-43T    MWH-1       120
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
39    AXCP-78    MWH-1       145

MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
9     TMI-43T    MWH-1       120
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
39    AXCP-78    MWH-1       145

In [ ]:
#delete the rows where quantity<=25
# drop method is used to delete or drop or remove the rows

ind = np.where(df.Quantity<=25)
ind

(array([ 8, 16]),)

In [ ]:
mydf = df.drop(ind[0])
mydf

#mydf is the dataframe in which the quantity<25 rows are removed

MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
1     AXCP-78    MWH-1        67
2     LXCV-21    MWH-2        27
3     AXCP-78    MWH-5        65
4     AXCP-78    MWH-4        36
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
15    GCVB-79    MWH-2        87
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
22    DDBN-89    MWH-4        48
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
30    DDBN-89    MWH-4        27
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
34    GCVB-79    MWH-5        26
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [ ]:
mydf.shape

(48, 3)

In [ ]:
df.head()

MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [ ]:
#Add a column 'Status' to dataframe if quantity<=50 then the status is scrap if quantity>50 then it is useful
#create an array of quantity, then iterate using for loop and if else conditions and add the elements to another list y
#add that y list as a column in dataframe

x = np.array(df['Quantity'])

In [ ]:
len(x)

50

In [ ]:
y = []
for i in range(len(x)):
  if x[i]<=50:
    y.append("Scrap")
  else:
    y.append("Useful")

In [ ]:
y

['Scrap',
 'Useful',
 'Scrap',
 'Useful',
 'Scrap',
 'Useful',
 'Scrap',
 'Scrap',
 'Scrap',
 'Useful',
 'Scrap',
 'Useful',
 'Useful',
 'Scrap',
 'Useful',
 'Useful',
 'Scrap',
 'Useful',
 'Scrap',
 'Useful',
 'Scrap',
 'Useful',
 'Scrap',
 'Useful',
 'Useful',
 'Useful',
 'Useful',
 'Useful',
 'Scrap',
 'Useful',
 'Scrap',
 'Useful',
 'Scrap',
 'Useful',
 'Scrap',
 'Scrap',
 'Scrap',
 'Useful',
 'Useful',
 'Useful',
 'Scrap',
 'Useful',
 'Scrap',
 'Scrap',
 'Scrap',
 'Useful',
 'Useful',
 'Scrap',
 'Useful',
 'Scrap']

In [ ]:
df['Status'] = y

In [ ]:
df.head()

MaterialID Location  Quantity  Status
0    TMI-43T    MWH-4        34   Scrap
1    AXCP-78    MWH-1        67  Useful
2    LXCV-21    MWH-2        27   Scrap
3    AXCP-78    MWH-5        65  Useful
4    AXCP-78    MWH-4        36   Scrap

In [113]:
#selecting only required columns

mydf = df[['Location','Status']]
mydf.head()

Location  Status
0    MWH-4   Scrap
1    MWH-1  Useful
2    MWH-2   Scrap
3    MWH-5  Useful
4    MWH-4   Scrap

In [115]:
mydf = df.drop('Location',axis = 1) #axis =1 is used for column
mydf.head()

MaterialID  Quantity  Status
0    TMI-43T        34   Scrap
1    AXCP-78        67  Useful
2    LXCV-21        27   Scrap
3    AXCP-78        65  Useful
4    AXCP-78        36   Scrap

In [133]:
#to display the column names we use the command below

mydf.columns

Index(['MaterialID', 'Quantity', 'Status'], dtype='object')

In [134]:
#storing the column names in a list 'x'

x = list(mydf.columns)
x

['MaterialID', 'Quantity', 'Status']

In [135]:
#to change the column name from materialid to name

x[0] = 'Name'

In [136]:
mydf.columns = x
mydf.columns

Index(['Name', 'Quantity', 'Status'], dtype='object')

**DATA CLEANING:**
1st check: finding out the missing values

2nd checkpoint: finding out duplicate values
create two dataframes, one containg duplicate values
other containing non-duplicate values.

3rd check: Data Validation:(the rules are given by client)
          1st part: goes with numbers
          2nd part: goes with strings

Data Cleaning
Logic for data cleaning
1) When we import the data , even if somebody has give excel file still we have to use it as the csv file.
pd.read_excel('sheet_name')// sheet_name within the columns.
2) Rules will be given by the office or by the client.
3) we need to know is how to apply this on the dataframe.
4) First thing we have to check the presence of the absence value.
 the blank cell will be displayed as the NAN
 So we have to search for the NAN of adhar number than , we have to take the action on that.
5) Create the separte data spam.
we can send the client that in the first file we have this record and in the second file we have another values in the file , so we have to tell them to cross check the data file and validate it.
6) Data validation first part will be with numbers (ex : age column value should not be less than 18 and create the another dataframe for age less than 18.)
and second part will be checked with the string.
Another data validation , suppose we have the PAN number.
Rule of checking pan number : 1) Fist 5 char should be alphabet
                              2) next 4 char should be number
                              3) next 1 char should be alphabet
     for these we have to write the program.
Then we will write the program which are number which is not satifying the condition of the pan number and seperate the dataframe which is not the valid pan number records
we have to use the file as - emp_info file.

In [138]:
df = pd.read_excel('emp_info.xlsx')
df

Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A746      NaN  RF453432
4    Rishi  R475    Prodn  DF453278
5   Chetan   NaN      NaN  ER534867
6   Deepak   NaN  Quality  RF453432

In [139]:
#step 1: look for the missing values

ind = np.where(df['Deptt'].isnull())
ind

(array([3, 5]),)

In [145]:
#create two separate dataframes in which i)deptt values are not missing and 2)another dataframe in which deptt values are missing

#deptt values are not missing
df1 = df.drop(ind[0],axis=0)
df1

Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
4    Rishi  R475    Prodn  DF453278
6   Deepak   NaN  Quality  RF453432

In [147]:
#another dataframe in which deptt values are missing

df2 = df.iloc[ind]
df2

Name EmpID Deptt  Passport
3   Arjun  A746   NaN  RF453432
5  Chetan   NaN   NaN  ER534867

In [152]:
#where deppt is null or empid is null

ind = np.where((df['Deptt'].isnull()) | (df['EmpID'].isnull()))
ind

(array([3, 5, 6]),)

In [156]:
df3 = df.drop(ind[0],axis=0)
df3

Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
4    Rishi  R475    Prodn  DF453278

**To remove the missing values directly in whichever row they are present.**

In [158]:
#to remove the missing values directly in whichever row they are present.
#important one!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

mydf = df.dropna()
mydf

Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
4    Rishi  R475    Prodn  DF453278

In [159]:
df

Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A746      NaN  RF453432
4    Rishi  R475    Prodn  DF453278
5   Chetan   NaN      NaN  ER534867
6   Deepak   NaN  Quality  RF453432

STEP 2:
Checking and Removing duplicate values

In [161]:
ind = np.where(df['Passport'].duplicated(keep=False))
ind

(array([0, 2, 3, 4, 6]),)

In [164]:
#printing duplicate values

df.iloc[ind[0]]

Name EmpID    Deptt  Passport
0  Sudeep  A342  Quality  DF453278
2     NaN  J436    Admin  DF453278
3   Arjun  A746      NaN  RF453432
4   Rishi  R475    Prodn  DF453278
6  Deepak   NaN  Quality  RF453432

In [163]:
#dropping the duplicate rows

df.drop(ind[0],axis=0)

Name EmpID  Deptt  Passport
1  Ruchika  C578  Sales  CA567657
5   Chetan   NaN    NaN  ER534867

In [ ]:
#the first value in the duplicate values are not considered as duplicate value. It is printed for 1 time.
ind = np.where(df['Passport'].duplicated(keep='first'))

#the last value in the duplicate values are not considered as duplicate value. It is printed for 1 time.
ind = np.where(df['Passport'].duplicated(keep='last'))

**GROUP BY**

In [167]:
df = pd.read_excel('ERPData.xlsx')

In [169]:
df.head()

MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [170]:
grp1 = df.groupby('Location')

In [171]:
grp1.groups

#key is location name, values are the row indexes in which they are present

{'MWH-1': [1, 9, 10, 24, 25, 26, 39, 40, 41, 48, 49], 'MWH-2': [2, 7, 8, 15, 35, 36, 42, 45, 46], 'MWH-3': [14, 43, 44, 47], 'MWH-4': [0, 4, 5, 6, 11, 12, 13, 18, 19, 20, 21, 22, 30, 31, 32], 'MWH-5': [3, 16, 17, 23, 27, 28, 29, 33, 34, 37, 38]}

In [172]:
len(grp1.groups)

5

In [173]:
#dislaying the MWH-2 group

grp1.get_group('MWH-2')

MaterialID Location  Quantity
2     LXCV-21    MWH-2        27
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
15    GCVB-79    MWH-2        87
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
42    SDRT-67    MWH-2        31
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85

In [174]:
#finding out the mean value of each location (group)

grp1.agg(np.mean)

<ipython-input-174-f7ec2c7c12e9>:1: FutureWarning: The operation <function mean at 0x7fc6267212d0> failed on a column. If any error is raised, this will raise an exception in a future version of pandas. Drop these columns to avoid this warning.
  grp1.agg(np.mean)


Quantity
Location           
MWH-1     80.818182
MWH-2     44.111111
MWH-3     43.500000
MWH-4     48.533333
MWH-5     63.363636

In [175]:
#dislaying the size(materialid, quantity) of each location
grp1.agg(np.size)

MaterialID  Quantity
Location                      
MWH-1             11        11
MWH-2              9         9
MWH-3              4         4
MWH-4             15        15
MWH-5             11        11

In [176]:
grp1.agg(np.sum)

<ipython-input-176-986be20c3d0d>:1: FutureWarning: The operation <function sum at 0x7fc626713c70> failed on a column. If any error is raised, this will raise an exception in a future version of pandas. Drop these columns to avoid this warning.
  grp1.agg(np.sum)


Quantity
Location          
MWH-1          889
MWH-2          397
MWH-3          174
MWH-4          728
MWH-5          697

In [177]:
grp1.agg(np.max)

MaterialID  Quantity
Location                     
MWH-1       TMI-43T       152
MWH-2       TMI-43T        87
MWH-3       TMI-43T        65
MWH-4       TMI-43T        78
MWH-5       TMI-43T       112

In [179]:
grp1.agg(np.min)

MaterialID  Quantity
Location                     
MWH-1       AXCP-78        34
MWH-2       AXCP-78        10
MWH-3       AXCP-78        29
MWH-4       AXCP-78        27
MWH-5       AXCP-78        12

In [180]:
grp1.agg([np.sum,np.mean])

#displaying sum and mean of quantity only because material id is string.

<ipython-input-180-4955c6e6179d>:1: FutureWarning: ['MaterialID'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  grp1.agg([np.sum,np.mean])


Quantity           
              sum       mean
Location                    
MWH-1         889  80.818182
MWH-2         397  44.111111
MWH-3         174  43.500000
MWH-4         728  48.533333
MWH-5         697  63.363636

In [183]:
r = grp1.agg([np.sum,np.mean])


<ipython-input-183-7e10a0b6fae9>:1: FutureWarning: ['MaterialID'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  r = grp1.agg([np.sum,np.mean])


In [184]:
ind = np.where(r.index=='MWH-3')
#finding the index of 'MWH-3' to find its sum and mean

In [186]:
#finding the sum and mean of 'MWH-3'

r.iloc[ind]

Quantity      
              sum  mean
Location               
MWH-3         174  43.5

In [187]:
grp2 = df.groupby(['MaterialID','Location'])

#grouping by materialid and location

In [188]:
grp2.groups

#materialid is primary key(primary grouping) here since we wrote it first. the indexes are row indexes here.

{('AXCP-78', 'MWH-1'): [1, 24, 25, 39, 48], ('AXCP-78', 'MWH-2'): [46], ('AXCP-78', 'MWH-3'): [47], ('AXCP-78', 'MWH-4'): [4], ('AXCP-78', 'MWH-5'): [3, 37, 38], ('DDBN-89', 'MWH-1'): [26, 40, 49], ('DDBN-89', 'MWH-2'): [45], ('DDBN-89', 'MWH-3'): [43], ('DDBN-89', 'MWH-4'): [22, 30], ('DDBN-89', 'MWH-5'): [23], ('GCVB-79', 'MWH-2'): [8, 15, 35, 36], ('GCVB-79', 'MWH-5'): [34], ('LXCV-21', 'MWH-2'): [2], ('LXCV-21', 'MWH-3'): [44], ('LXCV-21', 'MWH-5'): [27, 28, 29], ('SDRT-67', 'MWH-1'): [10, 41], ('SDRT-67', 'MWH-2'): [42], ('SDRT-67', 'MWH-4'): [11], ('SDRT-67', 'MWH-5'): [16, 17], ('TMI-43T', 'MWH-1'): [9], ('TMI-43T', 'MWH-2'): [7], ('TMI-43T', 'MWH-3'): [14], ('TMI-43T', 'MWH-4'): [0, 5, 6, 12, 13, 18, 19, 20, 21, 31, 32], ('TMI-43T', 'MWH-5'): [33]}

In [190]:
grp3 = df.groupby(['Location','MaterialID'])
grp3.groups

#here location is the primary key.Indexes are row indexes

{('MWH-1', 'AXCP-78'): [1, 24, 25, 39, 48], ('MWH-1', 'DDBN-89'): [26, 40, 49], ('MWH-1', 'SDRT-67'): [10, 41], ('MWH-1', 'TMI-43T'): [9], ('MWH-2', 'AXCP-78'): [46], ('MWH-2', 'DDBN-89'): [45], ('MWH-2', 'GCVB-79'): [8, 15, 35, 36], ('MWH-2', 'LXCV-21'): [2], ('MWH-2', 'SDRT-67'): [42], ('MWH-2', 'TMI-43T'): [7], ('MWH-3', 'AXCP-78'): [47], ('MWH-3', 'DDBN-89'): [43], ('MWH-3', 'LXCV-21'): [44], ('MWH-3', 'TMI-43T'): [14], ('MWH-4', 'AXCP-78'): [4], ('MWH-4', 'DDBN-89'): [22, 30], ('MWH-4', 'SDRT-67'): [11], ('MWH-4', 'TMI-43T'): [0, 5, 6, 12, 13, 18, 19, 20, 21, 31, 32], ('MWH-5', 'AXCP-78'): [3, 37, 38], ('MWH-5', 'DDBN-89'): [23], ('MWH-5', 'GCVB-79'): [34], ('MWH-5', 'LXCV-21'): [27, 28, 29], ('MWH-5', 'SDRT-67'): [16, 17], ('MWH-5', 'TMI-43T'): [33]}

In [192]:
grp2.agg([np.sum,np.size])

Quantity     
                         sum size
MaterialID Location              
AXCP-78    MWH-1         548    5
           MWH-2          85    1
           MWH-3          29    1
           MWH-4          36    1
           MWH-5         200    3
DDBN-89    MWH-1         130    3
           MWH-2          69    1
           MWH-3          38    1
           MWH-4          75    2
           MWH-5          71    1
GCVB-79    MWH-2         156    4
           MWH-5          26    1
LXCV-21    MWH-2          27    1
           MWH-3          42    1
           MWH-5         174    3
SDRT-67    MWH-1          91    2
           MWH-2          31    1
           MWH-4          58    1
           MWH-5         114    2
TMI-43T    MWH-1         120    1
           MWH-2          29    1
           MWH-3          65    1
           MWH-4         559   11
           MWH-5         112    1

In [193]:
grp3.agg([np.sum,np.size])

Quantity     
                         sum size
Location MaterialID              
MWH-1    AXCP-78         548    5
         DDBN-89         130    3
         SDRT-67          91    2
         TMI-43T         120    1
MWH-2    AXCP-78          85    1
         DDBN-89          69    1
         GCVB-79         156    4
         LXCV-21          27    1
         SDRT-67          31    1
         TMI-43T          29    1
MWH-3    AXCP-78          29    1
         DDBN-89          38    1
         LXCV-21          42    1
         TMI-43T          65    1
MWH-4    AXCP-78          36    1
         DDBN-89          75    2
         SDRT-67          58    1
         TMI-43T         559   11
MWH-5    AXCP-78         200    3
         DDBN-89          71    1
         GCVB-79          26    1
         LXCV-21         174    3
         SDRT-67         114    2
         TMI-43T         112    1

In [194]:
df

MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
1     AXCP-78    MWH-1        67
2     LXCV-21    MWH-2        27
3     AXCP-78    MWH-5        65
4     AXCP-78    MWH-4        36
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
15    GCVB-79    MWH-2        87
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
22    DDBN-89    MWH-4        48
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
30    DDBN-89    MWH-4        27
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
34    GCVB-79    MWH-5        26
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

**SORTING THE DATAFRAME:**

In [201]:
mydf = df.sort_values('Quantity')
mydf.head()

#Sorting in ascending order

MaterialID Location  Quantity
8     GCVB-79    MWH-2        10
16    SDRT-67    MWH-5        12
34    GCVB-79    MWH-5        26
2     LXCV-21    MWH-2        27
30    DDBN-89    MWH-4        27

In [197]:
mydf.tail()

MaterialID Location  Quantity
25    AXCP-78    MWH-1       109
33    TMI-43T    MWH-5       112
9     TMI-43T    MWH-1       120
39    AXCP-78    MWH-1       145
24    AXCP-78    MWH-1       152

In [202]:
#do the descending order

df.sort_values('Quantity',reverse=True)

TypeError: ignored

In [198]:
mydf.iloc[3]

MaterialID    LXCV-21
Location        MWH-2
Quantity           27
Name: 2, dtype: object

In [200]:
mydf = df.sort_values(['Location','MaterialID','Quantity'])
mydf

#first level sorting will be done on location then in location materialid is sorted(2nd level) then in materialid,
#quantity will be sorted(third level)

MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
48    AXCP-78    MWH-1        75
25    AXCP-78    MWH-1       109
39    AXCP-78    MWH-1       145
24    AXCP-78    MWH-1       152
40    DDBN-89    MWH-1        34
49    DDBN-89    MWH-1        39
26    DDBN-89    MWH-1        57
10    SDRT-67    MWH-1        34
41    SDRT-67    MWH-1        57
9     TMI-43T    MWH-1       120
46    AXCP-78    MWH-2        85
45    DDBN-89    MWH-2        69
8     GCVB-79    MWH-2        10
36    GCVB-79    MWH-2        28
35    GCVB-79    MWH-2        31
15    GCVB-79    MWH-2        87
2     LXCV-21    MWH-2        27
42    SDRT-67    MWH-2        31
7     TMI-43T    MWH-2        29
47    AXCP-78    MWH-3        29
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
14    TMI-43T    MWH-3        65
4     AXCP-78    MWH-4        36
30    DDBN-89    MWH-4        27
22    DDBN-89    MWH-4        48
11    SDRT-67    MWH-4        58
6     TMI-43T    MWH-4        31
13    TMI-43T    MWH-4        32
0     TMI-43T    MWH-4        34
18    TMI-43T    MWH-4        34
20    TMI-43T    MWH-4        39
32    TMI-43T    MWH-4        43
19    TMI-43T    MWH-4        52
31    TMI-43T    MWH-4        65
21    TMI-43T    MWH-4        75
12    TMI-43T    MWH-4        76
5     TMI-43T    MWH-4        78
3     AXCP-78    MWH-5        65
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
23    DDBN-89    MWH-5        71
34    GCVB-79    MWH-5        26
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
27    LXCV-21    MWH-5        83
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
33    TMI-43T    MWH-5       112

**2nd SESSION**
**MERGING: **

In [203]:
import numpy as np

In [1]:
import pandas as pd

In [21]:
df1 = pd.read_excel('locations.xlsx',sheet_name = 'Pune')

In [13]:
df2 = df1 = pd.read_excel('locations.xlsx',sheet_name='Mumbai')

In [22]:
df1

Name      Subject Grade
0   Rakesh       Python     A
1    Manoj     MLPython     C
2  Vaibhav   Statistics     B
3   Hitesh   CommSkills     A
4   Suyash  ProjectMgmt     B

In [19]:
df2

Name     Subject Grade
0   Vaibhav   Six Sigma     A
1   Deepika  Statistics     B
2     Arjun  CommSkills     A
3    Chetan      Python     A
4  Abhishek    MLPython     B

In [23]:
pd.merge(df1,df2, on = 'Subject', how = 'inner')

#on = common columns
#how = what kind of merging you want

Name_x     Subject Grade_x    Name_y Grade_y
0   Rakesh      Python       A    Chetan       A
1    Manoj    MLPython       C  Abhishek       B
2  Vaibhav  Statistics       B   Deepika       B
3   Hitesh  CommSkills       A     Arjun       A

In [24]:
pd.merge(df1,df2, on = 'Subject', how = 'outer')

#OUTER MERGE

Name_x      Subject Grade_x    Name_y Grade_y
0   Rakesh       Python       A    Chetan       A
1    Manoj     MLPython       C  Abhishek       B
2  Vaibhav   Statistics       B   Deepika       B
3   Hitesh   CommSkills       A     Arjun       A
4   Suyash  ProjectMgmt       B       NaN     NaN
5      NaN    Six Sigma     NaN   Vaibhav       A

In [27]:
pd.merge(df1,df2, on = 'Subject', how = 'left')

#LEFT MERGE
#the first dataframe(or left df) will be given more priority

Name_x      Subject Grade_x    Name_y Grade_y
0   Rakesh       Python       A    Chetan       A
1    Manoj     MLPython       C  Abhishek       B
2  Vaibhav   Statistics       B   Deepika       B
3   Hitesh   CommSkills       A     Arjun       A
4   Suyash  ProjectMgmt       B       NaN     NaN

In [26]:
pd.merge(df1,df2, on = 'Subject', how = 'right')

#RIGHT MERGE
#the second dataframe(or right df) will be given more priority

Name_x     Subject Grade_x    Name_y Grade_y
0      NaN   Six Sigma     NaN   Vaibhav       A
1  Vaibhav  Statistics       B   Deepika       B
2   Hitesh  CommSkills       A     Arjun       A
3   Rakesh      Python       A    Chetan       A
4    Manoj    MLPython       C  Abhishek       B

In [28]:
pd.merge(df1,df2,on=['Subject','Grade'],how='inner')

#both subject and grade must be same or common in inner

Name_x     Subject Grade   Name_y
0   Rakesh      Python     A   Chetan
1  Vaibhav  Statistics     B  Deepika
2   Hitesh  CommSkills     A    Arjun

In [29]:
pd.merge(df1,df2,on=['Subject','Grade'],how='outer')

Name_x      Subject Grade    Name_y
0   Rakesh       Python     A    Chetan
1    Manoj     MLPython     C       NaN
2  Vaibhav   Statistics     B   Deepika
3   Hitesh   CommSkills     A     Arjun
4   Suyash  ProjectMgmt     B       NaN
5      NaN    Six Sigma     A   Vaibhav
6      NaN     MLPython     B  Abhishek