In [ ]:
import numpy as np

In [ ]:
x = np.arange(10)

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x = np.arange(3,17,4)

In [ ]:
x

array([ 3,  7, 11, 15])

NumPy arange() is one of the array creation routines based on numerical ranges. It creates an instance of ndarray with evenly spaced values and returns the reference to it.

You can define the interval of the values contained in an array, space between them, and their type with four parameters of arange():

**numpy.arange(start, stop, step , dtype=None) -> numpy.ndarray**

The first three parameters determine the range of the values, while the fourth specifies the type of the elements:

start is the number (integer or decimal) that defines the first value in the array.
stop is the number that defines the end of the array and isn’t included in the array.
step is the number that defines the spacing (difference) between each two consecutive values in the array and defaults to 1.
dtype is the type of the elements of the output array and defaults to None.
step can’t be zero. Otherwise, you’ll get a ZeroDivisionError. You can’t move away anywhere from start if the increment or decrement is 0.

If dtype is omitted, arange() will try to deduce the type of the array elements from the types of start, stop, and step.

In [ ]:
x

array([ 3,  7, 11, 15])

In [ ]:
x = np.arange(40,6,-3)

In [ ]:
x

array([40, 37, 34, 31, 28, 25, 22, 19, 16, 13, 10,  7])

In [ ]:
x = np.array([3,5,4,7])

In [ ]:
x

array([3, 5, 4, 7])

In [ ]:
x+3

array([ 6,  8,  7, 10])

In [ ]:
y = [2,8,7,6]

In [ ]:
y = np.array(y)

In [ ]:
y= y+3

In [ ]:
y

array([ 5, 11, 10,  9])

Converting of list to array and VICEVERSA is called broadcasting.

In [ ]:
arr2d = np.array([[3,5,7,8],[1,4,3,6]])

In [ ]:
arr2d

array([[3, 5, 7, 8],
       [1, 4, 3, 6]])

In [ ]:
arr2d = np.array([[3,5,7,8],[1,4,3,6],[1,9,7,4]])

In [ ]:
arr2d

array([[3, 5, 7, 8],
       [1, 4, 3, 6],
       [1, 9, 7, 4]])

In [ ]:
arr3d = np.array([[[3,5,7,8],[]]])

In [ ]:
t = [2,4,3,6,5,7,8,9,1,2,3,5]

In [ ]:
len(t)

12

In [ ]:
t = np.array(t)

In [ ]:
arr2d = t.reshape(3,4)

# Reshaping an array

In [ ]:
arr2d

array([[2, 4, 3, 6],
       [5, 7, 8, 9],
       [1, 2, 3, 5]])

In [ ]:
t

array([2, 4, 3, 6, 5, 7, 8, 9, 1, 2, 3, 5])

In [ ]:
arr2d = t.reshape(2,6)

In [ ]:
arr2d

array([[2, 4, 3, 6, 5, 7],
       [8, 9, 1, 2, 3, 5]])

In [ ]:
arr2d = t.reshape(1,12)

In [ ]:
arr2d

array([[2, 4, 3, 6, 5, 7, 8, 9, 1, 2, 3, 5]])

In [ ]:
arr1d = np.array([3,7,6,4,8])

In [ ]:
len(arr1d)

5

In [ ]:
arr1d[3]

4

In [ ]:
arr1d

array([3, 7, 6, 4, 8])

In [ ]:
arr1d = np.append(arr1d,10)

#appending an element to the array

In [ ]:
arr1d

array([ 3,  7,  6,  4,  8, 10])

In [ ]:
arr1d = np.append(arr1d,8)

In [ ]:
arr1d

array([ 3,  7,  6,  4,  8, 10])

In [ ]:
arr1d = np.append(arr1d,8)

#8 is added at the end

In [ ]:
arr1d

array([ 3,  7,  6,  4,  8, 10,  8,  8])

In [ ]:
arr1d = np.insert(arr1d,3,5)

#3 is the index and 5 is the element
#np.insert(array_name,index_value,element)

In [ ]:
arr1d

array([ 3,  7,  6,  5,  4,  8, 10,  8])

In [ ]:
arr1d = np.delete(arr1d,4)

#executed two times
#np.delete(arr_name,element_index)

In [ ]:
arr1d

array([ 3,  7,  6,  5, 10,  8])

In [ ]:
list1 = [2,5,4,6]

In [ ]:
list2 = [3,9,8,1]

**Combining two lists as an array:**

In [ ]:
arr2d = np.array([list1,list2])

#**Combining two lists as an array**

In [ ]:
arr2d

array([[2, 5, 4, 6],
       [3, 9, 8, 1]])

In [ ]:
list3 = [4,8,7,2]

In [ ]:
arr2d = np.array([list1,list2,list3])

In [ ]:
arr2d

array([[2, 5, 4, 6],
       [3, 9, 8, 1],
       [4, 8, 7, 2]])

In [ ]:
arr2d[1]

array([3, 9, 8, 1])

In [ ]:
arr2d[0]

array([2, 5, 4, 6])

In [ ]:
arr2d[:,2] #3rd cloumn

array([4, 8, 7])

In [ ]:
arr2d[1][3]

1

In [ ]:
arr2d[1][3]=5

#updating the element or overwriting the element

In [ ]:
arr2d

array([[2, 5, 4, 6],
       [3, 9, 8, 5],
       [4, 8, 7, 2]])

CONCATENATING TWO ARRAYS:

In [ ]:
import numpy as np

In [ ]:
arr1d = np.array([3, 6, 5, 2, 7, 6, 9, 1])

In [ ]:
x = np.array([3,5,7,3,3,5,9,1,3])

In [ ]:
arr1d = np.concatenate((arr1d,x))

#concatenating two arrays np.concatenate((array1,array2)), lookout for the double brackets

In [ ]:
arr1d

array([3, 6, 5, 2, 7, 6, 9, 1, 3, 5, 7, 3, 3, 5, 9, 1, 3])

**UNIQUE VALUES IN AN ARRAY:**

In [ ]:
np.unique(arr1d) #unique values

array([1, 2, 3, 5, 6, 7, 9])

np.in1d() command:
#important

**np.in1d(array_name,[list of values]):**

O/P of  np.in1d() is list of true or false.

In [ ]:
np.in1d(arr1d,[2,7]) #imp command

array([False, False, False,  True,  True, False, False, False, False,
       False,  True, False, False, False, False, False, False])

In [ ]:
4 in np.unique(arr1d)

False

In [ ]:
np.where(np.in1d(arr1d,[2,7]))

(array([ 3,  4, 10]),)

In [ ]:
#we can add a list as a row in an array
#but we cant add list as a column because it is horizontal. we need to convert list to array first.

In [ ]:
newrow = [3,7,1,4]

In [ ]:
arr2d = np.vstack([arr2d,newrow])

np.vstack() = vertical stack;
--> Inorder to add list as a row we use np.vstack()

syntax: np.vstack(array_name,listname_to_add)

np.hstack() = horizontal stack
--> Inorder to add list as a column, we use np.hstack()

syntax: np.hstack(array_name,arrayname_to_add)

To add list as a column first reshape(convert it vertically) and then add using

np.hstack()

In [ ]:
arr2d

array([[2, 5, 4, 6],
       [3, 9, 8, 5],
       [4, 8, 7, 2],
       [3, 7, 1, 4]])

In [ ]:
newcol = np.array([3,8,7,2])

converting horzontal to vertical

In [ ]:
newcol = newcol.reshape(4,1)

In [ ]:
newcol

array([[3],
       [8],
       [7],
       [2]])

Now using np.hstack

In [ ]:
arr2d = np.hstack([arr2d,newcol])

In [ ]:
arr2d

array([[2, 5, 4, 6, 3],
       [3, 9, 8, 5, 8],
       [4, 8, 7, 2, 7],
       [3, 7, 1, 4, 2]])

**syntax : np.delete(arr_name,row_index or column_index, axis)**

axis = 0 ==> referring to row

axis = 1 ==> referring to column in delete()

In [ ]:
np.delete(arr2d,2,axis=0) #if assigment is used then permanent deletion happens.

array([[2, 5, 4, 6, 3],
       [3, 9, 8, 5, 8],
       [3, 7, 1, 4, 2]])

In [ ]:
arr2d

array([[2, 5, 4, 6, 3],
       [3, 9, 8, 5, 8],
       [4, 8, 7, 2, 7],
       [3, 7, 1, 4, 2]])

In [ ]:
np.delete(arr2d,2,axis=1)

array([[2, 5, 6, 3],
       [3, 9, 5, 8],
       [4, 8, 2, 7],
       [3, 7, 4, 2]])

**DATABASE MANAGEMENT COMMANDS:**

In [ ]:
arr1d = np.array([3,6,5,2,7,6,9,1])

In [ ]:
arr1d[:4] #Slicing

array([3, 6, 5, 2])

In [ ]:
arr1d[5:]

array([6, 9, 1])

In [ ]:
arr1d[2:6]

array([5, 2, 7, 6])

**OPERATIONAL DIFFERENCES BETWEEN LIST AND ARRAY:**

1) d = somelist
d%2 = error
but array don't give error
2) list is single dim, array is multidimensional
3) (**imp)  we can't extract 1st,4th,6th element using indexing in list but we can do it in array

In [ ]:
arr1d[[2,5,3]]

array([5, 6, 2])

In [ ]:
#for sorting we use sorted() command:
sorted_arr1d = sorted(arr1d)

In [ ]:
sorted_arr1d

[1, 2, 3, 5, 6, 6, 7, 9]

In [ ]:
#sorting in desc order:
sorted_arr1d = sorted(arr1d, reverse=True)

In [ ]:
sorted_arr1d

[9, 7, 6, 6, 5, 3, 2, 1]

In [ ]:
arr1d

array([3, 6, 5, 2, 7, 6, 9, 1])

finding out
1) how many values greater than 4

2) positions of that values (indexes)

3) what are those values

WHERE CMD:
Input to the np.where() is the logical condition Output to np.where() is the index where the condition is true

In [ ]:
ind = np.where(arr1d>=4)
#this gives output of indexes of the values >=4
#execute this in spyder some different output is coming with dtype=int64 added
#(array([1, 2, 4, 5, 6],dtype=int64),)

In [ ]:
ind
#this ind comes as touple o/p, the 1st element is the whole array
#after , if the array is 2d then columns indexes comes. here we're using 1d array only

(array([1, 2, 4, 5, 6]),)

In [ ]:
len(ind)

1

In [ ]:
len(ind[0])
#ind[0] is the first element of ind
#gives output of how many values are greater than 4 or the other 1st method is written below that is important

5

In [ ]:
ind

(array([1, 2, 4, 5, 6]),)

In [ ]:
(arr1d>=4).sum()
#This gives the no of values greater than 4 by directly using array. This is important

5

In [ ]:
arr1d[ind] #This gives the values that are greater than 4 in the array

array([6, 5, 7, 6, 9])

In [ ]:
arr2d #this we have defined in the above

array([[2, 5, 4, 6, 3],
       [3, 9, 8, 5, 8],
       [4, 8, 7, 2, 7],
       [3, 7, 1, 4, 2]])

In [ ]:
ind2 = np.where(arr2d>=4)

In [ ]:
ind2
#row indexes are in the first element
#column indexes are in the second element

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3]),
 array([1, 2, 3, 1, 2, 3, 4, 0, 1, 2, 4, 1, 3]))

In [ ]:
len(ind2)

2

In [ ]:
(arr2d>=4).sum()

13

In [ ]:
len(ind2[0]) #or len(ind2[1])

13

In [ ]:
arr2d[ind2] #the values

array([5, 4, 6, 9, 8, 5, 8, 4, 8, 7, 7, 7, 4])

In [ ]:
(arr2d[ind2])[0]

5

In [ ]:
arr2d[ind2[0]]

array([[2, 5, 4, 6, 3],
       [2, 5, 4, 6, 3],
       [2, 5, 4, 6, 3],
       [3, 9, 8, 5, 8],
       [3, 9, 8, 5, 8],
       [3, 9, 8, 5, 8],
       [3, 9, 8, 5, 8],
       [4, 8, 7, 2, 7],
       [4, 8, 7, 2, 7],
       [4, 8, 7, 2, 7],
       [4, 8, 7, 2, 7],
       [3, 7, 1, 4, 2],
       [3, 7, 1, 4, 2]])

In [ ]:
arr1d #upside w have concatenated two arrays into arr1d

array([3, 6, 5, 2, 7, 6, 9, 1, 3, 5, 7, 3, 3, 5, 9, 1, 3])

In [ ]:
np.unique(arr1d) #unique

array([1, 2, 3, 5, 6, 7, 9])

In [ ]:
np.in1d(arr1d,[2,7]) #imp command

array([False, False, False,  True,  True, False, False, False, False,
       False,  True, False, False, False, False, False, False])

In [ ]:
4 in np.unique(arr1d)

False

In [ ]:
np.where(np.in1d(arr1d,[2,7]))

(array([ 3,  4, 10]),)

In [ ]:
ind = np.where(np.in1d(arr1d,[2,7])) #important command to understand. understand this carefully

In [ ]:
ind

(array([ 3,  4, 10]),)

In [ ]:
x = np.array([4,7,6,3,9])

In [ ]:
y = np.array([1,4,5,7,8])

UNION (OR):

In [ ]:
np.union1d(x,y)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.union1d(y,x) #result is same

array([1, 3, 4, 5, 6, 7, 8, 9])

**INTERSECTION (AND):**

In [ ]:
np.intersect1d(x,y)

array([4, 7])

In [ ]:
np.intersect1d(y,x)

array([4, 7])

***np.in1d() between two arrays: ***

In [ ]:
np.in1d(x,y) #checks whether the values of x is present in y or not. (IMPORTANT)

array([ True,  True, False, False, False])

In [ ]:
np.in1d(y,x)

array([False,  True, False,  True, False])

**np.setdiff1d(x,y):** elements present in x but not in y

In [ ]:
np.setdiff1d(x,y)

array([3, 6, 9])

In [ ]:
np.setdiff1d(y,x)

array([1, 5, 8])

np.setxor1d(x,y): Array of exclusive(non common) elements in x and y


In [ ]:
np.setxor1d(x,y)

array([1, 3, 5, 6, 8, 9])

In [ ]:
np.setxor1d(y,x)

array([1, 3, 5, 6, 8, 9])