In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
import os

In [ ]:
os.getcwd()

'/content'

In [ ]:
os.chdir(r'/content/drive/MyDrive/STATSCDAC')

In [ ]:
os.getcwd()

'/content/drive/MyDrive/STATSCDAC'

In [ ]:
df1 = pd.read_excel('locations.xlsx',sheet_name='Salary')

In [ ]:
df2 = pd.read_excel('locations.xlsx',sheet_name='Deptt')

In [ ]:
df1

Name EmpID  Salary
0    Sudeep  A342      56
1   Deepika  J436      45
2    Chetan  B435      76
3  Abhishek  C234      47
4     Rishi  R475      38

In [ ]:
df2

Name EmpID        Deptt
0   Sudeep  A342      Quality
1  Ruchika  C578        Sales
2  Deepika  J436        Admin
3    Arjun  A342  Procurement
4    Rishi  R475        Prodn

In [ ]:
pd.merge(df1,df2)

#by default it will perform inner merge even if you don't write how = ''.

Name EmpID  Salary    Deptt
0   Sudeep  A342      56  Quality
1  Deepika  J436      45    Admin
2    Rishi  R475      38    Prodn

In [ ]:
pd.merge(df1,df2,how='inner')

Name EmpID  Salary    Deptt
0   Sudeep  A342      56  Quality
1  Deepika  J436      45    Admin
2    Rishi  R475      38    Prodn

In [ ]:
pd.merge(df1,df2,how='outer')

Name EmpID  Salary        Deptt
0    Sudeep  A342    56.0      Quality
1   Deepika  J436    45.0        Admin
2    Chetan  B435    76.0          NaN
3  Abhishek  C234    47.0          NaN
4     Rishi  R475    38.0        Prodn
5   Ruchika  C578     NaN        Sales
6     Arjun  A342     NaN  Procurement

In [ ]:
pd.merge(df1,df2,how='left')

#here sequencing is according to df1. look out

Name EmpID  Salary    Deptt
0    Sudeep  A342      56  Quality
1   Deepika  J436      45    Admin
2    Chetan  B435      76      NaN
3  Abhishek  C234      47      NaN
4     Rishi  R475      38    Prodn

In [ ]:
pd.merge(df1,df2,how='right')

Name EmpID  Salary        Deptt
0   Sudeep  A342    56.0      Quality
1  Ruchika  C578     NaN        Sales
2  Deepika  J436    45.0        Admin
3    Arjun  A342     NaN  Procurement
4    Rishi  R475    38.0        Prodn

In [ ]:
#practical application of merging


df1 = pd.read_excel('Materialinfo.xlsx',sheet_name='Inventory')

In [ ]:
df2 = pd.read_excel('Materialinfo.xlsx',sheet_name='Info')

In [ ]:
df1

MaterialID  Quantity
0           A        34
1           B        23
2           A        16
3           A        52
4           B        34
5           C        41
6           B        27
7           C        63
8           A        45
9           B        36
10          C        31
11          A        38

In [ ]:
df2

MaterialID  Rate
0          A  1200
1          B  1500
2          C  2400

In [ ]:
pd.merge(df1,df2)

MaterialID  Quantity  Rate
0           A        34  1200
1           A        16  1200
2           A        52  1200
3           A        45  1200
4           A        38  1200
5           B        23  1500
6           B        34  1500
7           B        27  1500
8           B        36  1500
9           C        41  2400
10          C        63  2400
11          C        31  2400

In [ ]:
pd.merge(df1,df2,how='left')

MaterialID  Quantity  Rate
0           A        34  1200
1           B        23  1500
2           A        16  1200
3           A        52  1200
4           B        34  1500
5           C        41  2400
6           B        27  1500
7           C        63  2400
8           A        45  1200
9           B        36  1500
10          C        31  2400
11          A        38  1200

**STATISTICS THEORY:**

There are three types of data in statistics point of view:
1)continuous data
2)Discrete data
3)Attribute data

***Continuous and Discrete data will always be numeric***

**1)continuous data:**
--> this is the data of numbers which have any no of decimal points are possible.
--> eg: temp of mumbai
    weight
eg2: time the local train takes to reach from kharghar to cst

**All measurements will be continuous data.**



**2)Discrete data**

--> The data where the numbers cannot have a decimal point.


eg: no of students in class(84.3 students are not possible, it's either 84 or 85)

-> this data is the result of **counting.**
-> this data is always a whole number

eg) no of stations between kharghar and cst
  no of countries
  no of chairs



**3)Attribute data**

--> This data is **characteristic.**
--> Attribute data can be a number or can be string.
--> If the data is string, then understand it is attribute data

eg: some use colab, some use spyder (counting according to the attribute)
colab = 15
spyder = 10

eg:2)
giving rating of ipl on a scale of 1-5(numbers as the attibutes have some restrictions) or A-E
but the count of no of persons who gave the particular rating is discrete data.

eg.3) Age is continuous but gender is attribute data.

drinking water(continuous data) from where you brought the water = canteen(attribute data) or colour of the bottle is blue(attribute data).

eg4) the type of class in which a person travels in the local train is attribute data. eg: normal,ac.



There are four types of scales in statistics:

**1)Nominal Scale:**

--> **The scale where we have multiple categories, the sequence of categories does n't matter.** or **Categories without logical order**

--> if there is an attribute data, that can be on Nominal scale

eg: name the languages you know. you'll speak hindi lang even if you give hindi any position in the list of languages you know


**2) Ordinal scale:**

--> **Categories with logical order**

eg: ranking (it is given on the order that 1-good, 5 bad (or) 1-bad, 5-good)

--> the order can change. but it will be in a logical order like 1-5 or 5-1.

--> The data is attribute data here

eg: give the rating of how much delay the mumbai local makes.(1 bad-5 very good)

**3)Interval scale:**

--> The scale where the number can be in decimals
--> **zero** does not mean absence of measurement.
we don't use this often

eg: temperature measurement.

**4) Ratio scale:**

-->We can perform all kind of measurements on this scale.
-->All the continuous and discrete data will be on ratio scale.
-->comparisions.
eg:harbour line trins are twice as delayed as central line trains.
eg: comparision of height, weight, experience etc


In [ ]:
grades = np.array(['A','C','D','A','A','B','C','A','B','B','B','A','C','B','A','A','B','C'])

#Categorical data on ordinal scale

In [ ]:
len(grades)

18

In [ ]:
np.unique(grades)

#getting the unique grades

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [ ]:
np.unique(grades, return_counts=True)

#count of students who got A,B,C,D grades
#counts of each grade is the discrete data here

(array(['A', 'B', 'C', 'D'], dtype='<U1'), array([7, 6, 4, 1]))

In [ ]:
grd_counts= np.unique(grades, return_counts=True)

In [ ]:
grd_counts

(array(['A', 'B', 'C', 'D'], dtype='<U1'), array([7, 6, 4, 1]))

In [ ]:
grd_counts[0]

#grades

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [ ]:
grd_counts[1]

#counts of grades

array([7, 6, 4, 1])

In [ ]:
import numpy as np

In [ ]:
grd_props = grd_counts[1]/len(grades)
grd_props

#proportions
#0.38 percent students got A grade, 0.33 % students got B grade etc

array([0.38888889, 0.33333333, 0.22222222, 0.05555556])

In [ ]:
grd_props = np.round(grd_props,3)
grd_props

array([0.389, 0.333, 0.222, 0.056])

In [ ]:
grd_pct = grd_props*100;
grd_pct

# 38 percent students got A grade, 33 % students got B grade etc

array([38.9, 33.3, 22.2,  5.6])

In [ ]:
np.cumsum(grd_pct)

#cumulative sum
#1st ele = 1st ele; 2nd ele = (1st ele + 2nd ele); 3rd ele = (1st ele+ 2nd ele+ 3rd ele) etc
# 72.2 % students got grade A and grade B

array([ 38.9,  72.2,  94.4, 100. ])

In [ ]:
x = np.array([45,78,23,56,112])
x

array([ 45,  78,  23,  56, 112])

In [ ]:
sorted(x)

[23, 45, 56, 78, 112]

In [ ]:
sorted(x,reverse=True)

[112, 78, 56, 45, 23]

In [ ]:
np.argsort(x)

#gives the indexes of the elements which are in ascending order

array([2, 0, 3, 1, 4])

DATA SUMMARIZATION:

It can be done using three techniques:

**1) Central Tendency:**
 to calculate central tendency we have **mean,median,mode**

**2) Variatiaon or Dispersion:**
--> range, inter-quartile range, variance, std deviation

**3) shape**
--> skewness and kurtosis

**MEAN:**

In [ ]:
mylist = [3,6,5,4,7,6,8,9,1,10,13,4,7,11,4,7,9]

In [ ]:
sum(mylist)/len(mylist)

6.705882352941177

In [ ]:
np.mean(mylist)

#mean

6.705882352941177

**WEIGHTED MEAN:**

**To calculate WEIGHTED MEAN: **
lets say, 10 numbers have value as 7, 15 numbers have value as 8, 23 numbers have value as 9, 8 numbers have values as 10

In [ ]:
freq = np.array([10,15,23,8])

In [ ]:
values = np.array([7,8,9,10])

In [ ]:
freq*values

array([ 70, 120, 207,  80])

In [ ]:
freq*values/sum(freq)

array([1.25      , 2.14285714, 3.69642857, 1.42857143])

In [ ]:
sum(freq*values/sum(freq))

#weighted mean

8.517857142857142

In [ ]:
#Calculating median

mylist

[3, 6, 5, 4, 7, 6, 8, 9, 1, 10, 13, 4, 7, 11, 4, 7, 9]

In [ ]:
len(mylist)

# we're getting odd value, so (17+1)/2 = 9 th element will be median

17

In [ ]:
sorted(mylist)[8]

#9th element is the median so we're giving 8 as index

7

In [ ]:
#INBUILT METHOD
np.median(mylist)

7.0

When to use  mean and median? #IMP EXAMPLE



In [ ]:
#eg:suppose the salaries in placements in a college are:

sal = [6,7,6,7,8,7,6,7,8,7,6,7,8,8,7,6,7,6,7,7,6,8]

In [ ]:
np.mean(sal)

6.909090909090909

In [ ]:
np.median(sal)

7.0

In [ ]:
new_sal = [6,7,6,7,8,7,6,7,8,7,6,7,8,8,7,6,7,6,7,7,6,8,54,50,52]

In [ ]:
np.mean(new_sal)

12.32

In [ ]:
np.median(new_sal)

# This figure is more close to average salary.
#Mathematically we should never use mean under any circumstance always use median.
#mean always misleads the decision.

7.0

Mean should be used when:

1)Data distribution is symmetric

2)Data should not have any extreme values(values that are far greater than the normal range. see the example above)

***If the data is symmetric then mean will be equal to median***



**MODE:**

1 mode: unimodal
2 modes: bimodal
3 modes: trimodal

**you need to import Counter library from Collections**

In [ ]:
from collections import Counter

In [ ]:
mylist

[3, 6, 5, 4, 7, 6, 8, 9, 1, 10, 13, 4, 7, 11, 4, 7, 9]

In [ ]:
Counter(mylist).most_common()

#calculating mode:prints the  highest frequency of an element in the list or array in descending order

[(4, 3),
 (7, 3),
 (6, 2),
 (9, 2),
 (3, 1),
 (5, 1),
 (8, 1),
 (1, 1),
 (10, 1),
 (13, 1),
 (11, 1)]

**VARIANCE OR DISPERSION:**

Range, Inter quartile range, variance, std deviation





**Range = max - min**

In [ ]:
mylist

[3, 6, 5, 4, 7, 6, 8, 9, 1, 10, 13, 4, 7, 11, 4, 7, 9]

In [ ]:
max(mylist)-min(mylist)

# Range = max - min

12

In [ ]:
x = [1,4,4,7,5,8,9,3,10]

In [ ]:
max(x)-min(x)

9

In [ ]:
y = [1,4,4,4,4,4,4,4,10]

In [ ]:
max(y)-min(y)

9

range of x and y is same. so range can be misleading.

**Drawbacks of range:**

1) Range uses only two out of multiple values in a list.
2) cal of range can get affected by the presence of extreme values.

**2) Inter Quartile Range:(IQR)**

**IQR = third quartile - first quartile (OR) 75th percentile - 25th percentile**

**EDA - Exploratory Data Analysis**
just wrote full form
Just casually lik diya!!!

In [ ]:
np.percentile(mylist,75) - np.percentile(mylist,25)

5.0

In [ ]:
x

[1, 4, 4, 7, 5, 8, 9, 3, 10]

In [ ]:
y

[1, 4, 4, 4, 4, 4, 4, 4, 10]

In [ ]:
np.percentile(x,75) - np.percentile(x,25)

4.0

In [ ]:
np.percentile(y,75) - np.percentile(y,25)

0.0

**To calculate the variation "standard deviation" is best!**
because variance unit is in sq.units.

std dev unit is consistent with the unit of data
eg: kilometer.

order of prefernce for consideration:
**std dev > variance > IQR > Range**

**VARIANCE:**

In [ ]:
x = [4,6,7,9,10,3,5,8,3,7]

***Population Variance:***

In [ ]:
#pop variance
np.var(x, ddof = 0)

5.36

***Sample Variance:***

In [ ]:
#Sample variance
np.var(x, ddof = 1)

5.955555555555556

***Population Standard Deviation using Population Variance***:

In [ ]:
#pop std dev
np.var(x, ddof = 0)**0.5

2.3151673805580453

***Population Standard Deviation:***

In [ ]:
np.std(x) #population std deviation

2.3151673805580453

***Sample Standard Deviation:***

In [ ]:
np.std(x, ddof = 1) #sample standard deviation

2.440400695696417